wandb_version: 1

BatchNorm:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1670912719.469908
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.13.6
      8:
      - 5
batch_size:
  desc: null
  value: 64
config_name:
  desc: null
  value: mynet_balanced
data:
  desc: null
  value: balanced
drop_out:
  desc: null
  value: false
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: null
optimizer:
  desc: null
  value: null
transform:
  desc: null
  value: false
