wandb_version: 1

BatchNorm:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1670935932.307568
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.13.6
      8:
      - 5
batch_size:
  desc: null
  value: 64
config_name:
  desc: null
  value: mynet_pro
data:
  desc: null
  value: pro
epochs:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: mynet
optimizer:
  desc: null
  value: null
transform:
  desc: null
  value: false
